### PR TITLE
Perform aws partition lookup for arn

### PR DESCRIPTION
**Pull request by bwmetcalf**
## what
* Instead of requiring the user to define arn_format for gov or china regions, lookup the partition in this module

## why
* Makes using this module easier

Fixes https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket/issues/44

### CODE REVIEW

**Comment by bwmetcalf** [comment]
Looks like auto_format failed, but I'm not sure why.

**Comment by bwmetcalf** [comment]
@woz5999

**Comment by woz5999** [comment]
@aknysh can you please review this?

**Comment by woz5999** [comment]
@aknysh @Nuru can someone please review/merge before more conflicts get introduced?

**Review by woz5999 — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]

**Comment by woz5999** [comment]
thanks @Gowiem !

**Pull request merged**
