### PR TITLE
Add custom policies

### LINKED ISSUE #19: policy variable doesn't accept input for a custom bucket policy
We want to add arns to the bucket policy after creation, and could find no way to add a custom policy.   The first time a run occurs, the bucket policy gets populated, but only with the existing accounts.

If you try to add a custom policy, it gets ignored.

As a workaround, I configured a normal input and then point that to a valid json with all of our account arns.

```terraform
  #policy                             = join("", data.aws_iam_policy_document.default.*.json)
  policy                             = var.policy
```

What would be ideal though is if it worked both ways.  So first create the default policy, and then if you define a policy that added whatever you needed:

`policy    = file("policies/cloudtrail-bucket.json")`

Or even better a list of arns to add to the policy dynamically.

### PR DESCRIPTION
**Pull request by bkero**
## what
* Allows the `policy` variable to be used in a useful way to set a custom S3 bucket policy
* Conditionally the data resource for the unused default bucket policy

## why
* Issue #19 outlines why this is required
* I have tested this change and found it to sufficiently create a custom S3 bucket policy sufficient for oganization-level writing.

Closes #19

### CODE REVIEW

**Comment by nitrocode** [comment]
Could we use something like `source_json` instead of this ?

See PR https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/pull/10

**Comment by bkero** [comment]
> Could

I've added a commit to rework this as you advise.

**Review by jamengual — DISMISSED** [review]

**Review by osterman — APPROVED** [review]

**Pull request merged**
